### ISSUE TITLE
Document usage for Knex

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/cloud-sql-nodejs-connector#111]
Issue to track interest in support for [Knex.js](https://knexjs.org/) with the Cloud SQL Node.js Connector.

Upvoting this issue 👍 will help us prioritize support.

**Comment by jackwotherspoon** [comment]
@ruyadorno if this is already supported we should change the title to `Document support for Knex` or something similar 😄

**Comment by ruyadorno** [comment]
Either that or just close this issue, I'm leaning more towards the former 😊 I believe it's going to be super useful to have examples / samples that showcase usage of the connector with many of these popular higher-level ORMs / libraries but I believe our original intention with these set of issues was really to make sure we investigate and queue up work necessary to support these libraries and that I believe has been accomplished if we confirmed Knex support.

**Comment by jackwotherspoon** [comment]
Sounds good, let's re-name this issue then to track adding a Knex usage sample either in the README or someplace better within the repo 👍

**Comment by jackwotherspoon** [comment]
Looks like Knex is supported already so updated title to reflect documenting a small sample usage. As discussed offline with @ruyadorno maybe an `examples` folder with basic usages of known drivers/ORMS would be best. That way we don't overcrowd the README.
