### ISSUE TITLE
Document how to use TypeORM

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/cloud-sql-nodejs-connector#112]
Issue to track interest in support for [TypeORM](https://typeorm.io/) with the Cloud SQL Node.js Connector.

Upvoting this issue 👍 will help us prioritize support.

**Comment by tjhiggins** [comment]
Seems to work in typeorm if you use the extra block: 

```ts
const connector = new Connector();
const clientOpts = await connector.getOptions({
  instanceConnectionName: '<connection_name>',
  ipType: IpAddressTypes.PRIVATE,
  authType: AuthTypes.IAM,
});

return {
  type: 'postgres',

  username: '<username>',
  database: '<database>',

  extra: {
    ...clientOpts,
    max: 5,
  },

  synchronize: true,
  autoLoadEntities: true,
};
```

**Comment by enocom** [comment]
That's great news. In that case, this is just a docs issue.

**Comment by jackwotherspoon** [comment]
FYI: TypeORM actually also supports automatic IAM authentication without the need for the use of this Connector library at all. https://github.com/typeorm/typeorm/issues/4724 

You can leverage passing a function to the `password` field in order to access a new access token to be used for IAM authentication.

**Comment by chadxz** [comment]
seems to me the connector option with the configuration shared by @tjhiggins is lower maintenance and better supported.

**Comment by enocom** [comment]
Both are feasible options. It depends on a person's appetite for adopting a Connector vs a generic Postgres interface.

**Comment by edosrecki** [comment]
@jackwotherspoon, @chadxz, @enocom, @tjhiggins 

`typeorm` uses `mssql` driver, whose current version (v9.3.2) uses `tedious@^15.0.1`, which does not support `connector` property. Therefore, following does **not** work:

```ts
new DataSource({
    type: 'mssql',
    host: '0.0.0.0', // dummy due to tedious bug
    username: 'my-user'
    password: 'my-password',
    database: 'my-database',
    extra: {
      options: {
        ...clientOpts,
      },
    },
  })
```

However, I see that upgrade of `tedious` in `mssql` has just been merged (https://github.com/tediousjs/node-mssql/commit/4968b3bf9c791be0a750b0b1edbc08344d9b3786). Once this is released, the aforementioned snippet will work.

**Comment by edosrecki** [comment]
Ah, of course, this was released in a new major version of `mssql`, v10. 

However, `typeorm` officially only supports `mssql@v9` (https://github.com/typeorm/typeorm/blob/befe4f9cbf17139bfaba83ae8a00e56b071df334/package.json#L152C23-L152C23).

Before, `typeorm` updates the `peerDependency` version for `mssql`, we cannot say that connector works with it.

**Comment by edosrecki** [comment]
Created PR in `typeorm` to support `mssql@10`: https://github.com/typeorm/typeorm/pull/10356

cc: @jackwotherspoon, @chadxz, @enocom, @tjhiggins

**Comment by jackwotherspoon** [comment]
> Created PR in `typeorm` to support `mssql@10`: [typeorm/typeorm#10356](https://github.com/typeorm/typeorm/pull/10356)

Wow! Thanks so much @edosrecki we really appreciate the contributions you are making 😄

**Comment by edosrecki** [comment]
Happy to contribute. I discovered a bug in `typeorm` tests which blocks this PR from becoming green, so let's see how responsive the team there is to roll this all out, but I guess it might take some time. 😄

**Comment by ruyadorno** [comment]
That sounds good 👍  we'll keep a close eye on that PR 👀

**Comment by weilinzung** [comment]
> Seems to work in typeorm if you use the extra block:
> 
> ```ts
> const connector = new Connector();
> const clientOpts = await connector.getOptions({
>   instanceConnectionName: '<connection_name>',
>   ipType: IpAddressTypes.PRIVATE,
>   authType: AuthTypes.IAM,
> });
> 
> return {
>   type: 'postgres',
> 
>   username: '<username>',
>   database: '<database>',
> 
>   extra: {
>     ...clientOpts,
>     max: 5,
>   },
> 
>   synchronize: true,
>   autoLoadEntities: true,
> };
> ```

@tjhiggins Is working for you with Typeorm? We are using mysql2 with Typeorm v2, but not working at all after deploying to Cloud Run.

```
    extra: {
                ...driverConnectorOptions
              }
```

```
"No repository for \"TestForm\" was found. Looks like this entity is not registered in current \"default\" connection?",
```

**Comment by tjhiggins** [comment]
> > Seems to work in typeorm if you use the extra block:
> > ```
> > const connector = new Connector();
> > const clientOpts = await connector.getOptions({
> >   instanceConnectionName: '<connection_name>',
> >   ipType: IpAddressTypes.PRIVATE,
> >   authType: AuthTypes.IAM,
> > });
> > 
> > return {
> >   type: 'postgres',
> > 
> >   username: '<username>',
> >   database: '<database>',
> > 
> >   extra: {
> >     ...clientOpts,
> >     max: 5,
> >   },
> > 
> >   synchronize: true,
> >   autoLoadEntities: true,
> > };
> > ```
> 
> @tjhiggins Is working for you with Typeorm? We are using mysql2 with Typeorm v2, but not working at all after deploying to Cloud Run.
> 
> ```
>     extra: {
>                 ...driverConnectorOptions
>               }
> ```
> 
> ```
> "No repository for \"TestForm\" was found. Looks like this entity is not registered in current \"default\" connection?",
> ```

I can only confirm it worked with postgres. It seems like it's still an issue with MySQL based on:
https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/112#issuecomment-1721281236

**Comment by edosrecki** [comment]
@weilinzung, @tjhiggins

It works with ALL drivers, however, not **officially** with SQL Server (`mssql` library) since it only supports v9, but v10 is required for Connector to work. But, you can force install `mssql@10` (to suppress npm errors saying that you are using wrong peer dependency) and it will work. But some people might not want to do that in production.

**Comment by enocom** [comment]
@ruyadorno shall we open an issue for pg-native support? Since it uses libpq under the hood, I wouldn't expect the connector to work with it.

**Comment by ruyadorno** [comment]
> @ruyadorno shall we open an issue for pg-native support? Since it uses libpq under the hood, I wouldn't expect the connector to work with it.

it might also be an opportunity to wait and see if the community will ask for it instead
