### ISSUE TITLE
Make `ipType` optional and default to Public IP

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/cloud-sql-nodejs-connector#126]
Currently `ipType` option is required when configuring the Connector. However, it should be optional and default to `"PUBLIC"` so that users can omit it from their Connector configurations.

Ref: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/main/src/connector.ts#L166

Also we should update our docstrings as part of this PR. They mention the old `type` which is now called `ipType`. https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/main/src/connector.ts#L27

**Comment by ruyadorno** [comment]
good catch! 👍
