### ISSUE TITLE
Investigate and document connection pooling options for SQL Server

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/cloud-sql-nodejs-connector#140]
Tedious does not support connection pooling natively [docs reference](https://tediousjs.github.io/tedious/api.html) It suggests using [tedious-connection-pool](https://github.com/tediousjs/tedious-connection-pool) for pooling, however this package is dead and has not been maintained in over 6 years 😢 

We should investigate potential solutions so that we can document how to use connection pooling for SQL Server as it is a best practice for production workloads.

Potential leads:
- [node-mssql](https://github.com/tediousjs/node-mssql) is built on top of tedious, so now that we support tedious we might also get support for `mssql` which has native connection pooling.
- could attempt to use a generic pooler such as [node-pool](https://github.com/coopernurse/node-pool) however this also seems to be not actively maintained

**Comment by ruyadorno** [comment]
After a few discussions with the team, the consensus is to focus on `mssql` as the recommended pooling library alternative for **SQL Server**, with that in mind I already started a conversation on updating `mssql` to update its version of `tedious` to a recent one with support to the **Cloud SQL Node.js Connector** (ref: https://github.com/tediousjs/node-mssql/pull/1500).

Let's follow up the conversation on properly documenting that in https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/154
