### ISSUE TITLE
Update README to clarify cloud-sql-proxy

### ISSUE THREAD

**Issue by bsgilber** [GoogleCloudPlatform/cloud-sql-nodejs-connector#141]
## Description
While reading through issues that touched on usage of this project with Cloud Run I ran across this [comment](https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/58#issuecomment-1542269454)

> No you do not need to also run the cloud-sql-proxy with this library. This library is meant as a native alternative to running the cloud-sql-proxy as it contains all the same functionality but as an npm package.

and was pleasantly surprised. However from the available Cloud Sql docs available I was under the impression that `cloud-sql-proxy` was a requirement to connect locally.

## Solution

A re-statement of the comment or its intent would be fine -- no you do not need to use cloud-sql-proxy to connect to Cloud Sql when using this package.

## Additional Context

Nada - thanks for this!

**Comment by enocom** [comment]
You're completely correct -- the Connector here is meant to be an in-process replacement for the Proxy. We'll find a way to make that clear in the README.

**Comment by jackwotherspoon** [comment]
@bsgilber I added a note to README specifying language connectors are a direct alternative to Cloud SQL Auth Proxy. We are also currently going through some updates to our Google Cloud official docs to make this more clear for users.

Hope this helps, thanks for filing the bug! 😄

**Comment by bsgilber** [comment]
Thanks for the quick turnaround @jackwotherspoon!
