### ISSUE TITLE
Force refresh connection info on connection failure

### ISSUE THREAD

**Issue by ruyadorno** [GoogleCloudPlatform/cloud-sql-nodejs-connector#186]
## Feature Description

We need to make sure the refresh logic in the Node.js connector aligns with the other Cloud SQL Connectors (Go, Python, Java). 

Note that the [CloudSQLInstance already have a refresh method](../blob/main/src/cloud-sql-instance.ts#L78) that may or may not be equivalent to the force-refresh API from other connectors.

**Comment by enocom** [comment]
The semantics of this should be:

- if a socket connection fails, force refresh
- if a TLS handshake fails, force refresh.

Force refresh means:
- Cancel the next refresh operation (unless it's already in progress)
- Save the current connection info if it still has a valid certificate
- if the current connection info's certificate is invalid (expired), then discard it and replace it with the next refresh.
