### ISSUE TITLE
Bad refresh should fail silently if metadata and cert are still valid

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/cloud-sql-nodejs-connector#201]
I believe the current node connector will blow up and fail if a background refresh fails. If metadata and cert are still valid while a background refresh fails, a user should still be able to successfully connect until the valid metadata and cert expire, allowing for more background refreshes to occur and hopefully self-correct itself.

This may potentially work as is but tests should be added to verify. Otherwise a [`isValid`](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/main/internal/cloudsql/instance.go#L110) or similar function may be beneficial in the Node connector.

**Comment by enocom** [comment]
If the refresh fails in the background, it shouldn't kill the whole process. It should keep trying following the force refresh pattern.  If the initial connection attempt fails, then the Connector should throw an other.

So initial attempt -> OK to throw an exception
Subsequent attempts (in the background) -> Not OK to throw an exception
