### ISSUE TITLE
GitHub Worklow for PR from a Fork does not checkout PR code

### ISSUE THREAD

**Issue by edosrecki** [GoogleCloudPlatform/cloud-sql-nodejs-connector#216]
## Bug Description

When a PR is opened from a repository fork, and repository maintainers add a label `tests: run`, GitHub Actions executes a workflow that runs tests. However, this workflow checks out the latest commit on a default branch of the target repository (not a repository fork). Therefore, test are not actually run against the code submitted by a contributor.

This is by design:

> pull_request_target runs in the context of the target repository of the PR, rather than in the merge commit. This means the standard checkout action uses the target repository to prevent accidental usage of the user supplied code.

It can be easily validated by checking the logs of a workflow execution on one of the PRs submitted from a repository fork.

Therefore, parameters need to be provided to `actions/checkout` action to check out the PR head commit.

## Code

https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/993d5d893454d2768d138a3edca714f4468a443d/.github/workflows/tests.yml#L71

**Comment by jackwotherspoon** [comment]
Good catch! Not sure how I missed this previously, fixed in linked PR
