### ISSUE TITLE
support for new user creation on the cloudsql instance

### ISSUE THREAD

**Issue by Anoupz** [GoogleCloudPlatform/cloud-sql-nodejs-connector#229]
## Question

Does this lib have support to create users on the cloud SQL instance? 

## Additional Context

If via API we need to add users to cloud SQL instance, is that possible? This library already using sqladmin_v1beta4 which does allow user CRUD.

**Comment by edosrecki** [comment]
@Anoupz That is not the scope of this library, and you can achieve DB user creation in plenty of ways already (e.g. using API directly, using language-specific SDKs, Terraform, and many other tools).

**Comment by Anoupz** [comment]
> @Anoupz That is not the scope of this library, and you can achieve DB user creation in plenty of ways already (e.g. using API directly, using language-specific SDKs, Terraform, and many other tools).

Got it thanks
