### ISSUE TITLE
Automatic IAM AuthN

### ISSUE THREAD

**Issue by ruyadorno** [GoogleCloudPlatform/cloud-sql-nodejs-connector#58]
## Feature Description

Add support to connect to a Cloud SQL instance using IAM auth.

**Comment by Dudesons** [comment]
Hi @ruyadorno @enocom , I'm very interesting to use this feature, do you have an idea approximately when this one will be available ?

**Comment by enocom** [comment]
We're starting this work this week. ;-)

cc @shubha-rajan

**Comment by siddhsql** [comment]
This issue will add IAM auth support to Node.js connector. I am glad to see that. BUT...

Let's say we deploy our application as a Cloud Run app. The cloud run app spins up a Docker container. The IAM credentials in the host VM do NOT propagate to the Docker container. Consequently the IAM auth will fail in a Cloud Run app. How do plan to handle that?

**Comment by enocom** [comment]
The IAM principal (not credentials) do propagate to app in the container. If you'd like to open a separate "question" issue, I can elaborate on details.

**Comment by siddhsql** [comment]
I have created this issue: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/80. thanks

**Comment by siddhsql** [comment]
@ruyadorno thanks for completing this. are you able to answer the question in https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/80?

**Comment by siddhsql** [comment]
for us it does not work. this is our code:

```
const { Connector } = require('@google-cloud/cloud-sql-connector');
const {Pool} = require('pg');

const connector = new Connector();

const clientOpts = connector.getOptions({
  instanceConnectionName: 'project:region:instance',  
  type: 'PUBLIC', // doc says to use ipType but that does not work
  authType: 'IAM'
}).then(opts => {
    connect(opts).then(() => console.log("done")).catch(e => handleError(e));
}).catch(e => handleError(e));

connect = async (clientOpts) => {
    console.log(clientOpts);
    const pool = new Pool({
        ...clientOpts,
        user: 'xyz@google.com',
        password: '',
        database: 'rrm',
        max: 5
      });
      const {rows} = await pool.query('SELECT NOW()');
      console.table(rows); // prints returned time value from server
      
      await pool.end();
      connector.close();
}

handleError = (e) => {
    console.log(e);
    console.log(e.stack);
}
```

if `password` is `null` or `empty` we get:

```
» node index.js             130 ↵
{ stream: [Function: stream], ssl: false }
error: empty password returned by client
    at Parser.parseErrorMessage (/Users/xxx/node/cloudsql-iam-auth-test/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/xxx/node/cloudsql-iam-auth-test/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/xxx/node/cloudsql-iam-auth-test/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/Users/xxx/node/cloudsql-iam-auth-test/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 96,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '781',
  routine: 'recv_password_packet'
}
```

and if a dummy password is given we get:

```
 » node index.js             130 ↵
error: Cloud SQL IAM user authentication failed for user "xxx.com"
    at Parser.parseErrorMessage (/Users/xxx/node/cloudsql-iam-auth-test/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/xxx/node/cloudsql-iam-auth-test/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/xxx/node/cloudsql-iam-auth-test/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/Users/xxx/node/cloudsql-iam-auth-test/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 123,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '351',
  routine: 'auth_failed'
}
```

**Comment by siddhsql** [comment]
one question i have is that `connector.getOptions` just returns a

```
{ stream: [Function: stream], ssl: false }
```

based on this how does `pg` know what password to use and where to connect in:

```
const pool = new Pool({
        ...clientOpts,
        user: 'xxx',       
        database: 'xxx',
        max: 5
      });
```

**Comment by Dudesons** [comment]
When this feature will be released ?

**Comment by jackwotherspoon** [comment]
@siddhsql @Dudesons We will be cutting a new release either today or tomorrow which will include the IAM AuthN feature! 😄

@siddhsql This may be the cause of your issue? How are you installing the package currently? If you were installing directly from npm registry then that release does not include IAM AuthN currently.

If you install from Github directly you can try out the latest features prior to the official npm release.
```sh
npm install https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector.git
```

**Comment by siddhsql** [comment]
yes this is indeed the reason. could you help me understand a few things:

1. the question i have posted above
2. when we run locally and use this library, do we also need to run the
cloud-sql-proxy program on the local machine?
3. if answer is yes, who runs the cloud-sql-proxy program on cloud run?
does google do that automatically?

**Comment by jackwotherspoon** [comment]
Hi @siddhsql1 let me clarify your questions for you!

> based on this how does pg know what password to use and where to connect in:

@ruyadorno  may be able to add more context but both `pg` and `mysql2` have a factory method that allows them to create a connection from a pre-configured socket. This is what the stream returns as you can see [here with getSocket](https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/main/src/connector.ts#L206) 

So when you do:
```js
const clientOpts = await connector.getOptions({
  instanceConnectionName: 'my-project:region:my-instance',
  ipType: 'PUBLIC', 
});
```
You are creating a stream that returns secure SSL sockets that enable connections to your Cloud SQL instance when passed to the connection pooling libraries such as `pg`.

> 2. when we run locally and use this library, do we also need to run the
cloud-sql-proxy program on the local machine?
> 3. if answer is yes, who runs the cloud-sql-proxy program on cloud run?
does google do that automatically?

No you do not need to also run the `cloud-sql-proxy` with this library. This library is meant as a native alternative to running the `cloud-sql-proxy` as it contains all the same functionality but as an npm package.

**Comment by siddhsql** [comment]
thanks @jackwotherspoon yo are right. i did my own investigation yesterday and stepped through the code confirming what you say. i tested the library 0.3.0 and it does work. there is one problem though. we use sequelize and cannot connect to cloud sql with iam credentials since sequelize does not pass the stream to pg. i guess adding support for sequelize will be outside the scope of this project if i am not mistaken.

**Comment by jackwotherspoon** [comment]
@siddhsql I went ahead and created a new feature request for sequelize support, feel free to upvote it to show your interest

**Comment by siddhsql** [comment]
Thanks Jack. I upvoted it. @jackwotherspoon

**Comment by CarltonK** [comment]
I tried it now this way with Prisma and still got an error

```
  private async setupConnection() {
    this._logger.info('Setting up connector', this._ctx);
    const dbSecrets = JSON.parse(
      this._configService.get<string>('DATABASE_SECRETS'),
    );
    this._logger.info(`${JSON.stringify(dbSecrets)}`, this._ctx);

    try {
      const socketPath = resolve('.s.PGSQL.5432');
      await this._connector.startLocalProxy({
        instanceConnectionName: dbSecrets.connectionName,
        ipType: IpAddressTypes.PRIVATE,
        authType: AuthTypes.IAM,
        listenOptions: { path: socketPath },
      });
    } catch (error) {
      this._logger.info('Error: (Connector Setup)', this._ctx);
      throw error;
    }

    await this.$disconnect(); // Ensure no active connection before reconfiguring.
    this._connectorClose = this._connector.close.bind(this._connector);
    await this.$connect();
  }
```

Consider support for Prisma

**Comment by jackwotherspoon** [comment]
> I tried it now this way with Prisma and still got an error

@CarltonK do you mind opening up a new issue on this repo detailing your error? That way we can help you with your issue without cluttering an old and closed issue 😄 

Please provide the environment you are running in (local machine, Cloud Run, App Engine etc.), the exact error message you are seeing, along with your application code (above code).

Thanks in advance!
