### ISSUE TITLE
Support credentials file

### ISSUE THREAD

**Issue by ruyadorno** [GoogleCloudPlatform/cloud-sql-nodejs-connector#59]
## Feature Description

A Cloud SQL Node.js Connector user should be able to point to a custom credentials file to connect to Cloud SQL Admin APIs.

**Comment by enocom** [comment]
I think we're already good here. 

People can set `GOOGLE_APPLICATION_CREDENTIALS` and be done with it.

https://github.com/googleapis/google-cloud-node#download-your-service-account-credentials-json-file

**Comment by edosrecki** [comment]
@ruyadorno @enocom This already works fine, it is how I used it locally for testing purposes.
