### ISSUE TITLE
Ensure default TCP keep alive is set to 30s

### ISSUE THREAD

**Issue by ruyadorno** [GoogleCloudPlatform/cloud-sql-nodejs-connector#63]
## Feature Description

Add the ability to customize the keep alive value use to connect to Cloud SQL instances. Make sure there's a default value of 30s used for any new connection.

**Comment by enocom** [comment]
Whether we add support for customizing the keepalive seems less important. Let's treat this as ensuring the default is set and correct.

**Comment by ruyadorno** [comment]
Landed in https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/pull/73
